Added lint action
eoinmcbennett/moves-like-swagger-api pull request #10
Opened 2023-11-08 10:56 UTC by eoinmcbennett

2023-11-08 15:46 UTC, chrisknos approved these changes

2023-11-08 15:55 UTC, shaunganley requested changes

2023-11-08 15:55 UTC, shaunganley commented on checkstyle-suppressions.xml
> +    <suppress checks="WhitespaceAround" files="."/>
please remove suppressions and fix :)

2023-11-09 09:49 UTC, shaunganley approved these changes

2023-11-09 12:01 UTC, merged