002 view job spec
eoinmcbennett/moves-like-swagger-api pull request #18
Opened 2023-11-14 13:25 UTC by 40175096

2023-11-14 13:34 UTC, eoinmcbennett requested changes

2023-11-14 13:34 UTC, eoinmcbennett commented on src/main/java/org/kainos/ea/team2/api/JobService.java
> +    }
Class instance variable should be same name as constructor one

2023-11-14 13:34 UTC, eoinmcbennett commented on src/main/java/org/kainos/ea/team2/exception/FailedToGetException.java
> +
Add a constructor a message here

2023-11-14 13:34 UTC, eoinmcbennett commented on src/main/java/org/kainos/ea/team2/exception/JobDoesNotExistException.java
> +}
Add a constructor a message here

2023-11-14 13:57 UTC, eoinmcbennett approved these changes

2023-11-15 09:42 UTC, shaunganley approved these changes

2023-11-15 09:42 UTC, shaunganley commented on sqlfiles/003-002-view-job-spec.sql
> +    ADD COLUMN sharepoint_link TEXT
might not need this length of column

2023-11-15 09:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/team2/cli/JobSpecificationResponse.java
> +
is there any other info we might want to display on the frontend screen? role name perhaps?

2023-11-15 12:10 UTC, merged