041 Authentication Implementation
eoinmcbennett/moves-like-swagger-api pull request #21
Opened 2023-11-16 16:08 UTC by eoinmcbennett

2023-11-17 12:37 UTC, 40175096 approved these changes

2023-11-20 10:27 UTC, shaunganley requested changes

2023-11-20 10:27 UTC, shaunganley commented on src/test/java/org/kainos/ea/team2/integration/JobIntegrationTest.java
> +                .request().header("Authorization", "Bearer " + jwt).get(List.class);
can you add integration tests for each endpoint without this header and verify unauthorized returned?

2023-11-20 10:27 UTC, shaunganley commented on src/main/java/org/kainos/ea/team2/cli/Authorise.java
> +    UserRole value() default UserRole.User;
should we be defaulting this? wouldn't that provide access to endpoints they shouldn't be able to access?

2023-11-20 10:27 UTC, shaunganley commented on src/main/java/org/kainos/ea/team2/resources/JobController.java
> +    @Authorise(UserRole.User)
admin should also have access to this endpoint

2023-11-20 10:27 UTC, shaunganley commented on src/main/java/org/kainos/ea/team2/resources/JobController.java
> +    @Authorise(UserRole.User)
admin should also have access to this endpoint

2023-11-22 10:00 UTC, shaunganley approved these changes
if you had to add a new role I think it would break all of this auth but we can call that tech debt for now :)

2023-11-23 10:32 UTC, merged